version: ""

formatter: markdown table

name: terraform-aws-cloudtrail

content: |-
  # terraform-aws-cloudtrail

  GitHub: [StratusGrid/terraform-aws-cloudtrail](https://github.com/StratusGrid/terraform-aws-cloudtrail)

  This module sets up CloudTrail for an AWS account, including writing to CloudWatch, an S3 bucket and an SNS topic.

  # Examples

  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```

  ---

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  ## Contributors
  - Wesley Kirkland [wesleykirklandsg](https://github.com/wesleykirklandsg)
  - Module originally forked from [Quinovas](https://github.com/QuiNovas)

  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - resources
    - inputs
    - outputs
    - providers
    - requirements

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
